source ~/.bashrc
export PATH=~/bin:$PATH
export PATH=$HOME/.elixir-install/installs/otp/27.2.3/bin:$PATH
export PATH=$HOME/.elixir-install/installs/elixir/1.18.3-otp-27/bin:$PATH
export FLYCTL_INSTALL="/home/nook/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"

# generated by Git for Windows
source ~/.bash_vars.sh
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# cd ~/Travelpass/travelpass.com

# function to generate aliases from variables stored in bash_vars.sh
# this function is defined in .bash_vars.sh
source_aliases

# Git
alias addp="git add . && git restore --staged app/gqlClient.server.tsx vite.config.ts"
alias gc="git commit -m"
alias gco="git checkout"
alias gcob="git checkout -b"
alias pull="git pull"
alias pullx="git pull origin master --rebase -Xtheirs"
alias push="git push"
alias pushf="git push origin HEAD -f"
alias revise="git commit --amend --no-edit"
alias stat="git status"

function gitfilter() {
# shows all files with directory specified by argument 2, which have been modified by author
# specified by argument 1. Argument 2 can be empty to default to "/"
    local dir_name
    if [ -z "$2" ]; then
        dir_name="/"
    else
        dir_name="$2"
    fi
    git log --author="$1" --pretty=format: --name-only | sort -u | grep "$dir_name"
}

function renamelast() {
    local new_name=$1
    git commit --amend -m "$new_name"
}

function sb() {
# search branches
    local SEARCH_TERM

    if [ -n "$1" ]; then
        SEARCH_TERM="$1"
    else
        SEARCH_TERM=""
    fi

    echo "Search term was: $SEARCH_TERM"

    git branch | grep $SEARCH_TERM && git branch -r | grep $SEARCH_TERM
}

function vcommit() {
    # verbose commit
    local commit_message=$1
    local commit_description=$2
    git commit -m "$commit_message" -m "" -m "$commit_description"
}

# Plaza
#  alias work="cd ~/plaza && start /mnt/c/Users/Christopher/AppData/Local/slack/slack.exe && open https://linear.app/plaza-eng/ && open https://github.com/plaza-ai && sshplaza"
alias bard="cd ~/plaza/bard"
alias volo="cd ~/plaza/volo"
alias xan="cd ~/plaza/xanathar"
alias gcloud-volo="gcloud config set project volo-439521 && gcloud auth application-default login && ./cloud-sql-proxy --port 5431 volo-439521:us-west1:volo-dev"
alias sshplaza="eval '$(ssh-agent -s)' && ssh-add ~/.ssh/id_plaza_wsl"

# Portal
alias portal="cd ~/dev-portal-v2-cli && npm run prod -- nookoid"


function lint() {
# $# means number of arguments passed in
# $@ means all arguments passed in
# -gt means greater than
  if [ "$#" -gt 0 ]; then
    for file in "$@"; do
      npx eslint "$file" --fix
      git diff "$file"
    done
  else
    local changed_files
    changed_files=$(git diff --name-only)

    if [ -z "$changed_files" ]; then
      echo "No changes detected, running eslint on all files"
      npx eslint "./app/**/*.{ts,tsx,js,jsx}" --fix
    else
      echo "Linting changed files"
      for file in $changed_files; do
        if [[ $file == *".ts" || $file == *".tsx" || $file == *".js" || $file == *".jsx" ]]; then
          npx eslint "$file" --fix
        fi
      done
    fi
  fi
}

# Misc
alias activate="python3 -m venv .venv; source .venv/bin/activate; pip3 install -r requirements.txt;"
alias editbash="cursor ~/.bash_profile"
alias editbashvars="cursor ~/.bash_vars.sh"
alias updatebash="source ~/.bash_profile && source ~/.bashrc && source ~/.bash_vars.sh"



